name: story_app
description: "Submission Dicoding awal"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# --Packages---
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  #penyimpanan sementara
  shared_preferences: ^2.2.0
  #Request API
  http: ^1.1.0
  #State Management
  provider: ^6.0.5
  #Image
  image_picker: ^1.0.2
  #massage
  fluttertoast: ^8.2.2

# ---------- End Packages ---------- #


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  
# ---------- Local Assets ---------- #
  assets:
    - assets/
# ---------- End Flutter ---------- #