name: story_app
description: "Submission Dicoding awal"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# --Packages---
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #penyimpanan sementara
  shared_preferences: ^2.2.0
  #Request API
  http: ^1.3.0
  #State Management
  provider: ^6.0.5
  #Image
  image_picker: ^1.0.2
  #massage
  fluttertoast: ^8.2.2
 # Library untuk pemrograman fungsional.
  dartz: ^0.10.1 
  # Render file SVG.
  flutter_svg: ^2.0.17 
  # Geocoding dan reverse geocoding.
  geocoding: ^3.0.0 
  # Navigasi dan routing.
  go_router: ^14.8.1 
  # Font dari Google Fonts.
  google_fonts: ^6.2.1 
  # Google Maps di Flutter.
  google_maps_flutter: ^2.10.1 
  # Manipulasi gambar.
  image: ^4.5.4 
  # Serialisasi JSON.
  json_annotation: ^4.9.0 
  # Efek "pull to refresh".
  liquid_pull_to_refresh: ^3.0.1 
  # Data lokasi perangkat.
  location: ^7.0.1 
  # Efek shimmer (loading).
  shimmer: ^3.0.0
# ---------- End Packages ---------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true

  # ---------- Local Assets ---------- #
  assets:
    - assets/images/
# ---------- End Flutter ---------- #
